// This file was auto-generated by ML.NET Model Builder. 

using System;
using FantasyPremierLeagueML.Model;

namespace FantasyPremierLeagueML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Isvalid2017 = 1F,
                Minutes2017 = 2161F,
                Points2017 = 112F,
                Influence2017 = 640.6F,
                Creativity2017 = 1287.5F,
                Threat2017 = 555F,
                Isvalid2018 = 1F,
                Minutes2018 = 1732F,
                Points2018 = 89F,
                Influence2018 = 429.6F,
                Creativity2018 = 714.2F,
                Threat2018 = 254F,
                Isvalid2019 = 1F,
                Minutes2019 = 1439F,
                Points2019 = 53F,
                Influence2019 = 223.6F,
                Creativity2019 = 582.9F,
                Threat2019 = 190F,
                Isvalidgw_less_1 = 0F,
                Minutesgw_less_1 = 0F,
                Pointsgw_less_1 = 0F,
                Influencegw_less_1 = 0F,
                Creativitygw_less_1 = 0F,
                Threatgw_less_1 = 0F,
                Athomegw_less_1 = 0F,
                Difficultygw_less_1 = 0F,
                Isvalidgw_less_2 = 0F,
                Minutesgw_less_2 = 0F,
                Pointsgw_less_2 = 0F,
                Influencegw_less_2 = 0F,
                Creativitygw_less_2 = 0F,
                Threatgw_less_2 = 0F,
                Athomegw_less_2 = 0F,
                Difficultygw_less_2 = 0F,
                Isvalidgw_less_3 = 0F,
                Minutesgw_less_3 = 0F,
                Pointsgw_less_3 = 0F,
                Influencegw_less_3 = 0F,
                Creativitygw_less_3 = 0F,
                Threatgw_less_3 = 0F,
                Athomegw_less_3 = 0F,
                Difficultygw_less_3 = 0F,
                Isvalidgw_less_4 = 0F,
                Minutesgw_less_4 = 0F,
                Pointsgw_less_4 = 0F,
                Influencegw_less_4 = 0F,
                Creativitygw_less_4 = 0F,
                Threatgw_less_4 = 0F,
                Athomegw_less_4 = 0F,
                Difficultygw_less_4 = 0F,
                Isvalidgw_less_5 = 0F,
                Minutesgw_less_5 = 0F,
                Pointsgw_less_5 = 0F,
                Influencegw_less_5 = 0F,
                Creativitygw_less_5 = 0F,
                Threatgw_less_5 = 0F,
                Athomegw_less_5 = 0F,
                Difficultygw_less_5 = 0F,
                Isvalidgw_less_6 = 0F,
                Minutesgw_less_6 = 0F,
                Pointsgw_less_6 = 0F,
                Influencegw_less_6 = 0F,
                Creativitygw_less_6 = 0F,
                Threatgw_less_6 = 0F,
                Athomegw_less_6 = 0F,
                Difficultygw_less_6 = 0F,
                Isvalidgw_less_7 = 0F,
                Minutesgw_less_7 = 0F,
                Pointsgw_less_7 = 0F,
                Influencegw_less_7 = 0F,
                Creativitygw_less_7 = 0F,
                Threatgw_less_7 = 0F,
                Athomegw_less_7 = 0F,
                Difficultygw_less_7 = 0F,
                Isvalidgw_less_8 = 0F,
                Minutesgw_less_8 = 0F,
                Pointsgw_less_8 = 0F,
                Influencegw_less_8 = 0F,
                Creativitygw_less_8 = 0F,
                Threatgw_less_8 = 0F,
                Athomegw_less_8 = 0F,
                Difficultygw_less_8 = 0F,
                Isvalidgw_less_9 = 0F,
                Minutesgw_less_9 = 0F,
                Pointsgw_less_9 = 0F,
                Influencegw_less_9 = 0F,
                Creativitygw_less_9 = 0F,
                Threatgw_less_9 = 0F,
                Athomegw_less_9 = 0F,
                Difficultygw_less_9 = 0F,
                Isvalidgw_less_10 = 0F,
                Minutesgw_less_10 = 0F,
                Pointsgw_less_10 = 0F,
                Influencegw_less_10 = 0F,
                Creativitygw_less_10 = 0F,
                Threatgw_less_10 = 0F,
                Athomegw_less_10 = 0F,
                Difficultygw_less_10 = 0F,
                Isvalidgw_less_11 = 0F,
                Minutesgw_less_11 = 0F,
                Pointsgw_less_11 = 0F,
                Influencegw_less_11 = 0F,
                Creativitygw_less_11 = 0F,
                Threatgw_less_11 = 0F,
                Athomegw_less_11 = 0F,
                Difficultygw_less_11 = 0F,
                Isvalidgw_less_12 = 0F,
                Minutesgw_less_12 = 0F,
                Pointsgw_less_12 = 0F,
                Influencegw_less_12 = 0F,
                Creativitygw_less_12 = 0F,
                Threatgw_less_12 = 0F,
                Athomegw_less_12 = 0F,
                Difficultygw_less_12 = 0F,
                Isvalidgw_less_13 = 0F,
                Minutesgw_less_13 = 0F,
                Pointsgw_less_13 = 0F,
                Influencegw_less_13 = 0F,
                Creativitygw_less_13 = 0F,
                Threatgw_less_13 = 0F,
                Athomegw_less_13 = 0F,
                Difficultygw_less_13 = 0F,
                Playerid = 1F,
                Teamid = 1F,
                Position = 3F,
                Selectedby = 0.6F,
                Transfersin = 0F,
                Transfersout = 0F,
                Diff = 2F,
                Home = @"0",
                Value = 70F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Points with predicted Points from sample data...\n\n");
            Console.WriteLine($"Isvalid2017: {sampleData.Isvalid2017}");
            Console.WriteLine($"Minutes2017: {sampleData.Minutes2017}");
            Console.WriteLine($"Points2017: {sampleData.Points2017}");
            Console.WriteLine($"Influence2017: {sampleData.Influence2017}");
            Console.WriteLine($"Creativity2017: {sampleData.Creativity2017}");
            Console.WriteLine($"Threat2017: {sampleData.Threat2017}");
            Console.WriteLine($"Isvalid2018: {sampleData.Isvalid2018}");
            Console.WriteLine($"Minutes2018: {sampleData.Minutes2018}");
            Console.WriteLine($"Points2018: {sampleData.Points2018}");
            Console.WriteLine($"Influence2018: {sampleData.Influence2018}");
            Console.WriteLine($"Creativity2018: {sampleData.Creativity2018}");
            Console.WriteLine($"Threat2018: {sampleData.Threat2018}");
            Console.WriteLine($"Isvalid2019: {sampleData.Isvalid2019}");
            Console.WriteLine($"Minutes2019: {sampleData.Minutes2019}");
            Console.WriteLine($"Points2019: {sampleData.Points2019}");
            Console.WriteLine($"Influence2019: {sampleData.Influence2019}");
            Console.WriteLine($"Creativity2019: {sampleData.Creativity2019}");
            Console.WriteLine($"Threat2019: {sampleData.Threat2019}");
            Console.WriteLine($"Isvalidgw_less_1: {sampleData.Isvalidgw_less_1}");
            Console.WriteLine($"Minutesgw_less_1: {sampleData.Minutesgw_less_1}");
            Console.WriteLine($"Pointsgw_less_1: {sampleData.Pointsgw_less_1}");
            Console.WriteLine($"Influencegw_less_1: {sampleData.Influencegw_less_1}");
            Console.WriteLine($"Creativitygw_less_1: {sampleData.Creativitygw_less_1}");
            Console.WriteLine($"Threatgw_less_1: {sampleData.Threatgw_less_1}");
            Console.WriteLine($"Athomegw_less_1: {sampleData.Athomegw_less_1}");
            Console.WriteLine($"Difficultygw_less_1: {sampleData.Difficultygw_less_1}");
            Console.WriteLine($"Isvalidgw_less_2: {sampleData.Isvalidgw_less_2}");
            Console.WriteLine($"Minutesgw_less_2: {sampleData.Minutesgw_less_2}");
            Console.WriteLine($"Pointsgw_less_2: {sampleData.Pointsgw_less_2}");
            Console.WriteLine($"Influencegw_less_2: {sampleData.Influencegw_less_2}");
            Console.WriteLine($"Creativitygw_less_2: {sampleData.Creativitygw_less_2}");
            Console.WriteLine($"Threatgw_less_2: {sampleData.Threatgw_less_2}");
            Console.WriteLine($"Athomegw_less_2: {sampleData.Athomegw_less_2}");
            Console.WriteLine($"Difficultygw_less_2: {sampleData.Difficultygw_less_2}");
            Console.WriteLine($"Isvalidgw_less_3: {sampleData.Isvalidgw_less_3}");
            Console.WriteLine($"Minutesgw_less_3: {sampleData.Minutesgw_less_3}");
            Console.WriteLine($"Pointsgw_less_3: {sampleData.Pointsgw_less_3}");
            Console.WriteLine($"Influencegw_less_3: {sampleData.Influencegw_less_3}");
            Console.WriteLine($"Creativitygw_less_3: {sampleData.Creativitygw_less_3}");
            Console.WriteLine($"Threatgw_less_3: {sampleData.Threatgw_less_3}");
            Console.WriteLine($"Athomegw_less_3: {sampleData.Athomegw_less_3}");
            Console.WriteLine($"Difficultygw_less_3: {sampleData.Difficultygw_less_3}");
            Console.WriteLine($"Isvalidgw_less_4: {sampleData.Isvalidgw_less_4}");
            Console.WriteLine($"Minutesgw_less_4: {sampleData.Minutesgw_less_4}");
            Console.WriteLine($"Pointsgw_less_4: {sampleData.Pointsgw_less_4}");
            Console.WriteLine($"Influencegw_less_4: {sampleData.Influencegw_less_4}");
            Console.WriteLine($"Creativitygw_less_4: {sampleData.Creativitygw_less_4}");
            Console.WriteLine($"Threatgw_less_4: {sampleData.Threatgw_less_4}");
            Console.WriteLine($"Athomegw_less_4: {sampleData.Athomegw_less_4}");
            Console.WriteLine($"Difficultygw_less_4: {sampleData.Difficultygw_less_4}");
            Console.WriteLine($"Isvalidgw_less_5: {sampleData.Isvalidgw_less_5}");
            Console.WriteLine($"Minutesgw_less_5: {sampleData.Minutesgw_less_5}");
            Console.WriteLine($"Pointsgw_less_5: {sampleData.Pointsgw_less_5}");
            Console.WriteLine($"Influencegw_less_5: {sampleData.Influencegw_less_5}");
            Console.WriteLine($"Creativitygw_less_5: {sampleData.Creativitygw_less_5}");
            Console.WriteLine($"Threatgw_less_5: {sampleData.Threatgw_less_5}");
            Console.WriteLine($"Athomegw_less_5: {sampleData.Athomegw_less_5}");
            Console.WriteLine($"Difficultygw_less_5: {sampleData.Difficultygw_less_5}");
            Console.WriteLine($"Isvalidgw_less_6: {sampleData.Isvalidgw_less_6}");
            Console.WriteLine($"Minutesgw_less_6: {sampleData.Minutesgw_less_6}");
            Console.WriteLine($"Pointsgw_less_6: {sampleData.Pointsgw_less_6}");
            Console.WriteLine($"Influencegw_less_6: {sampleData.Influencegw_less_6}");
            Console.WriteLine($"Creativitygw_less_6: {sampleData.Creativitygw_less_6}");
            Console.WriteLine($"Threatgw_less_6: {sampleData.Threatgw_less_6}");
            Console.WriteLine($"Athomegw_less_6: {sampleData.Athomegw_less_6}");
            Console.WriteLine($"Difficultygw_less_6: {sampleData.Difficultygw_less_6}");
            Console.WriteLine($"Isvalidgw_less_7: {sampleData.Isvalidgw_less_7}");
            Console.WriteLine($"Minutesgw_less_7: {sampleData.Minutesgw_less_7}");
            Console.WriteLine($"Pointsgw_less_7: {sampleData.Pointsgw_less_7}");
            Console.WriteLine($"Influencegw_less_7: {sampleData.Influencegw_less_7}");
            Console.WriteLine($"Creativitygw_less_7: {sampleData.Creativitygw_less_7}");
            Console.WriteLine($"Threatgw_less_7: {sampleData.Threatgw_less_7}");
            Console.WriteLine($"Athomegw_less_7: {sampleData.Athomegw_less_7}");
            Console.WriteLine($"Difficultygw_less_7: {sampleData.Difficultygw_less_7}");
            Console.WriteLine($"Isvalidgw_less_8: {sampleData.Isvalidgw_less_8}");
            Console.WriteLine($"Minutesgw_less_8: {sampleData.Minutesgw_less_8}");
            Console.WriteLine($"Pointsgw_less_8: {sampleData.Pointsgw_less_8}");
            Console.WriteLine($"Influencegw_less_8: {sampleData.Influencegw_less_8}");
            Console.WriteLine($"Creativitygw_less_8: {sampleData.Creativitygw_less_8}");
            Console.WriteLine($"Threatgw_less_8: {sampleData.Threatgw_less_8}");
            Console.WriteLine($"Athomegw_less_8: {sampleData.Athomegw_less_8}");
            Console.WriteLine($"Difficultygw_less_8: {sampleData.Difficultygw_less_8}");
            Console.WriteLine($"Isvalidgw_less_9: {sampleData.Isvalidgw_less_9}");
            Console.WriteLine($"Minutesgw_less_9: {sampleData.Minutesgw_less_9}");
            Console.WriteLine($"Pointsgw_less_9: {sampleData.Pointsgw_less_9}");
            Console.WriteLine($"Influencegw_less_9: {sampleData.Influencegw_less_9}");
            Console.WriteLine($"Creativitygw_less_9: {sampleData.Creativitygw_less_9}");
            Console.WriteLine($"Threatgw_less_9: {sampleData.Threatgw_less_9}");
            Console.WriteLine($"Athomegw_less_9: {sampleData.Athomegw_less_9}");
            Console.WriteLine($"Difficultygw_less_9: {sampleData.Difficultygw_less_9}");
            Console.WriteLine($"Isvalidgw_less_10: {sampleData.Isvalidgw_less_10}");
            Console.WriteLine($"Minutesgw_less_10: {sampleData.Minutesgw_less_10}");
            Console.WriteLine($"Pointsgw_less_10: {sampleData.Pointsgw_less_10}");
            Console.WriteLine($"Influencegw_less_10: {sampleData.Influencegw_less_10}");
            Console.WriteLine($"Creativitygw_less_10: {sampleData.Creativitygw_less_10}");
            Console.WriteLine($"Threatgw_less_10: {sampleData.Threatgw_less_10}");
            Console.WriteLine($"Athomegw_less_10: {sampleData.Athomegw_less_10}");
            Console.WriteLine($"Difficultygw_less_10: {sampleData.Difficultygw_less_10}");
            Console.WriteLine($"Isvalidgw_less_11: {sampleData.Isvalidgw_less_11}");
            Console.WriteLine($"Minutesgw_less_11: {sampleData.Minutesgw_less_11}");
            Console.WriteLine($"Pointsgw_less_11: {sampleData.Pointsgw_less_11}");
            Console.WriteLine($"Influencegw_less_11: {sampleData.Influencegw_less_11}");
            Console.WriteLine($"Creativitygw_less_11: {sampleData.Creativitygw_less_11}");
            Console.WriteLine($"Threatgw_less_11: {sampleData.Threatgw_less_11}");
            Console.WriteLine($"Athomegw_less_11: {sampleData.Athomegw_less_11}");
            Console.WriteLine($"Difficultygw_less_11: {sampleData.Difficultygw_less_11}");
            Console.WriteLine($"Isvalidgw_less_12: {sampleData.Isvalidgw_less_12}");
            Console.WriteLine($"Minutesgw_less_12: {sampleData.Minutesgw_less_12}");
            Console.WriteLine($"Pointsgw_less_12: {sampleData.Pointsgw_less_12}");
            Console.WriteLine($"Influencegw_less_12: {sampleData.Influencegw_less_12}");
            Console.WriteLine($"Creativitygw_less_12: {sampleData.Creativitygw_less_12}");
            Console.WriteLine($"Threatgw_less_12: {sampleData.Threatgw_less_12}");
            Console.WriteLine($"Athomegw_less_12: {sampleData.Athomegw_less_12}");
            Console.WriteLine($"Difficultygw_less_12: {sampleData.Difficultygw_less_12}");
            Console.WriteLine($"Isvalidgw_less_13: {sampleData.Isvalidgw_less_13}");
            Console.WriteLine($"Minutesgw_less_13: {sampleData.Minutesgw_less_13}");
            Console.WriteLine($"Pointsgw_less_13: {sampleData.Pointsgw_less_13}");
            Console.WriteLine($"Influencegw_less_13: {sampleData.Influencegw_less_13}");
            Console.WriteLine($"Creativitygw_less_13: {sampleData.Creativitygw_less_13}");
            Console.WriteLine($"Threatgw_less_13: {sampleData.Threatgw_less_13}");
            Console.WriteLine($"Athomegw_less_13: {sampleData.Athomegw_less_13}");
            Console.WriteLine($"Difficultygw_less_13: {sampleData.Difficultygw_less_13}");
            Console.WriteLine($"Playerid: {sampleData.Playerid}");
            Console.WriteLine($"Teamid: {sampleData.Teamid}");
            Console.WriteLine($"Position: {sampleData.Position}");
            Console.WriteLine($"Selectedby: {sampleData.Selectedby}");
            Console.WriteLine($"Transfersin: {sampleData.Transfersin}");
            Console.WriteLine($"Transfersout: {sampleData.Transfersout}");
            Console.WriteLine($"Diff: {sampleData.Diff}");
            Console.WriteLine($"Home: {sampleData.Home}");
            Console.WriteLine($"Value: {sampleData.Value}");
            Console.WriteLine($"\n\nPredicted Points: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
