// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FantasyPremierLeagueML.Model
{
    public class ModelInput
    {
        [ColumnName("mins2017"), LoadColumn(0)]
        public float Mins2017 { get; set; }


        [ColumnName("pts2017"), LoadColumn(1)]
        public float Pts2017 { get; set; }


        [ColumnName("valid2017"), LoadColumn(2)]
        public float Valid2017 { get; set; }


        [ColumnName("mins2018"), LoadColumn(3)]
        public float Mins2018 { get; set; }


        [ColumnName("pts2018"), LoadColumn(4)]
        public float Pts2018 { get; set; }


        [ColumnName("valid2018"), LoadColumn(5)]
        public float Valid2018 { get; set; }


        [ColumnName("mins2019"), LoadColumn(6)]
        public float Mins2019 { get; set; }


        [ColumnName("pts2019"), LoadColumn(7)]
        public float Pts2019 { get; set; }


        [ColumnName("valid2019"), LoadColumn(8)]
        public float Valid2019 { get; set; }


        [ColumnName("diff"), LoadColumn(9)]
        public float Diff { get; set; }


        [ColumnName("home"), LoadColumn(10)]
        public float Home { get; set; }


        [ColumnName("points"), LoadColumn(11)]
        public float Points { get; set; }


    }
}
